Try some darwin hacks

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -18,7 +18,11 @@ msg "* Downloading $TOOL_NAME release $ASDF_INSTALL_VERSION..."
 curl -fsSL -O -C - "$(release_url)" || fail "Could not download $(release_url)"
 
 #  Extract contents of tar.gz file into the download directory
-tar -xzf "$(release_file)" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $(release_file)"
+if [[ get_platform == 'darwin' ]]; then
+  installer -pkg myapp.pkg -target "$ASDF_DOWNLOAD_PATH"
+else
+  tar -xzf "$(release_file)" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $(release_file)"
+fi
 
 # Remove the tar.gz file since we don't need to keep it
 rm "${ASDF_DOWNLOAD_PATH}/$(release_file)"
