Get the installation script working

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -12,4 +12,17 @@ if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
   fail "asdf-$TOOL_NAME supports release installs only"
 fi
 
+(
+  mkdir -p "$ASDF_INSTALL_PATH"
+  cp -r "$ASDF_DOWNLOAD_PATH"/* "$ASDF_INSTALL_PATH"
+
+  local tool_cmd
+  tool_cmd="$(echo "$TOOL_TEST" | cut -d' ' -f1)"
+  test -x "$install_path/$tool_cmd" || fail "Expected $install_path/$tool_cmd to be executable."
+
+  echo "$TOOL_NAME $version installation was successful!"
+) || (
+  rm -rf "$install_path"
+  fail "An error occurred while installing $TOOL_NAME $version."
+)
 
